name = "trend-diary"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]
main = "./src/web/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true
head_sampling_rate = 1
