services:
  postgres:
    image: postgres:15.8
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/setup_config.sql:/docker-entrypoint-initdb.d/setup_config.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres # Supabase側で変更できず、Supabaseの設定と整合性を保つため
    command: postgres

volumes:
  postgres_data:
    driver: local
