name: Deploy Preview
description: Previewç’°å¢ƒã®ãƒ‡ãƒ—ãƒ­ã‚¤

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/deploy_preview.yml'
      - 'src/**'
      - 'public/**'
      - 'prisma/**'
      - 'functions/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node.jsã®æ§‹ç¯‰
        uses: ./.github/actions/setup_node
        with:
          node-version-file: .node-version

      - name: ãƒ“ãƒ«ãƒ‰
        run: npm run build

      - name: ãƒ‡ãƒ—ãƒ­ã‚¤
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy

      - name: PRã‚³ãƒ¡ãƒ³ãƒˆã‚’ä½œæˆãƒ»æ›´æ–°ã™ã‚‹
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: deploy-preview
          message: |
            ## ğŸš€ Preview ãƒ‡ãƒ—ãƒ­ã‚¤

            **ãƒ‡ãƒ—ãƒ­ã‚¤URL**: ${{ steps.deploy.outputs.url }}

            **ãƒ‡ãƒ—ãƒ­ã‚¤æ™‚é–“**: ${{ github.event.repository.updated_at }}

            <details>
              <summary>ãƒ‡ãƒ—ãƒ­ã‚¤å‡ºåŠ›ã®è©³ç´°</summary>
              
              ```
              ${{ steps.deploy.outputs.command-output }}
              ```
            </details>

  database:
    runs-on: ubuntu-latest
    environment: preview
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Node.jsã®æ§‹ç¯‰
        uses: ./.github/actions/setup_node
        with:
          node-version-file: .node-version

      - name: Prismaã®ãƒã‚¤ã‚°ãƒ¬ãƒ¼ã‚·ãƒ§ãƒ³
        run: npm run db:migrate:deploy
