name: E2E

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/e2e.yaml'
      - 'application/src/test/e2e/**'
      - 'application/src/web/client/routes/**'
      - 'application/package.json'
      - 'application/package-lock.json'

# カバレッジの可視化で、コメントを残すための権限
permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash
    working-directory: ./application

# 共通の設定を定義
env:
  NODE_VERSION_FILE: .node-version

jobs:
  test:
    name: Main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v4

      - name: Supabaseのセットアップ
        uses: ./.github/actions/setup_supabase

      - name: E2E環境のセットアップ
        uses: ./.github/actions/setup_e2e
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: E2Eテストの実行
        run: npm run e2e -- --pass-with-no-tests

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: application/src/test/e2e/playwright-report/
          retention-days: 30

  test-diff:
    name: Diff
    if: github.event_name == 'pull_request'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: setup-supabase
        name: Supabaseのセットアップ
        uses: ./.github/actions/setup_supabase

      - name: E2E環境のセットアップ
        uses: ./.github/actions/setup_e2e
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: E2Eテストの差分実行
        shell: bash
        run: |
          set -euo pipefail
          npm run e2e -- --reporter=github --only-changed=origin/$GITHUB_BASE_REF
