name: E2E Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/e2e.yaml'
      - 'src/test/e2e/**'
      - 'src/application/web/routes/**'
      - 'package.json'
      - 'package-lock.json'

# カバレッジの可視化で、コメントを残すための権限
permissions:
  contents: read
  pull-requests: write

# 連続push時に同じジョブが並列で実行されるのを防ぐ
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# 共通の設定を定義
env:
  NODE_VERSION_FILE: .node-version
  DATABASE_URL: postgresql://postgres:password@localhost:5432/postgres # Supabase側で変更できず、Supabaseの設定と整合性を保つため

jobs:
  e2e:
    # E2Eテストは時間がかかるため、タイムアウトを設定
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 完全な履歴を取得して差分比較できるようにする
      - name: Node.jsの構築
        uses: ./.github/actions/setup_node
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: Playwrightブラウザのキャッシュ
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - name: Playwrightのセットアップ
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install chromium --with-deps

      # ページの結合、シナリオテスト実施のためにDBが必要
      - name: PostgreSQLのセットアップ
        run: docker compose build && docker compose up -d

      - name: PostgreSQLが起動するまで待機
        uses: ./.github/actions/backoff
        with:
          command: 'docker exec $(docker ps -q -f name=postgres) pg_isready -U postgres'
          fail_command: docker compose down

      - name: DB Migration
        env:
          DIRECT_URL: ${{ env.DATABASE_URL }}
        run: npm run db:migrate

      - name: E2Eテストの差分実行
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          set -euo pipefail
          npm run e2e -- --reporter=github --only-changed=origin/$GITHUB_BASE_REF

      - name: E2Eテストの実行
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npm run e2e -- --pass-with-no-tests

      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !cancelled()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
