name: E2E

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/e2e.yaml'
      - 'src/test/e2e/**'
      - 'src/application/web/routes/**'
      - 'package.json'
      - 'package-lock.json'

# カバレッジの可視化で、コメントを残すための権限
permissions:
  contents: read
  pull-requests: write

# 連続push時に同じジョブが並列で実行されるのを防ぐ
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# 共通の設定を定義
env:
  NODE_VERSION_FILE: .node-version

jobs:
  test:
    name: Main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env: &postgres-env
      DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:54322/postgres
      DIRECT_URL: postgresql://postgres:postgres@127.0.0.1:54322/postgres
    services: &postgres-service
      postgres:
        image: postgres:15.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 54322:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: E2E環境のセットアップ
        uses: ./.github/actions/setup_e2e
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: E2Eテストの実行
        run: npm run e2e -- --pass-with-no-tests

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: src/test/e2e/playwright-report/
          retention-days: 30

  test-diff:
    name: Diff
    if: github.event_name == 'pull_request'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env: *postgres-env
    services: *postgres-service
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: E2E環境のセットアップ
        uses: ./.github/actions/setup_e2e
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: E2Eテストの差分実行
        shell: bash
        run: |
          set -euo pipefail
          npm run e2e -- --reporter=github --only-changed=origin/$GITHUB_BASE_REF
